[custom]
;emoji
emoji=!!import:https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/Clash_Emoji.txt

;排除
; exclude_remarks=(精简)
; exclude_remarks=(剩余流量|Traffic|到期时间|过期时间|Expire|官网地址|官方网址|官址|产品名称|套餐)
; exclude_remarks=(.*流量.*剩.*天)
; exclude_remarks=(备用官网|备用官址|备用网址)
; exclude_remarks=(订阅|TG群)
exclude_remarks=(Premium|premium)

;重命名
; rename_node=中港@中
; rename_node=豫港@豫
; rename_node=京港@京
; rename_node=京日@京
; rename_node=海港@海
; rename_node=广港@广
; rename_node=杭港@杭
; rename_node=杭日@杭
; rename_node=杭联@杭
; rename_node=沪港@沪
; rename_node=沪日@沪
; rename_node=京德@京
;设置规则标志位
;自定义
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/daili.list
ruleset=🌍 美股券商,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/financial.list
ruleset=🌍 美股券商,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/irs.list
ruleset=🎥 EMBY,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/MediaNode.list
ruleset=🎥 EMBY,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/plex.list
ruleset=🎥 EMBY,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/emby.list
ruleset=🌍 尚需直连,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/vps.list
ruleset=🎮 SteamCN,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎮 SteamCN,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
ruleset=🌍 开发相关,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/Developer.list
ruleset=🌍 开发相关,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Developer/Developer.list
ruleset=🌍 开发相关,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🌍 开发相关,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
; ruleset=🌍 开发相关,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/irs.list
ruleset=🎥 Exhentai,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EHGallery/EHGallery.list

; ruleset=🎶 Spotify,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
; ruleset=🎶 Tidal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TIDAL/TIDAL.list
ruleset=🌍 PT站点,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.list
ruleset=🌍 PT站点,https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/Ruleset/PrivateTracker.list

;默认
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list


; ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
; ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
; ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
; ruleset=🆎 AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
; ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
; ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list
; ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.list
; ruleset=🛡️ 隐私防护,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy.list
; ruleset=🛑 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ZhihuAds/ZhihuAds.list

ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=📢 谷歌,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=📢 谷歌,[]DOMAIN-SUFFIX,services.googleapis.cn
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCN.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTubeMusic/YouTubeMusic.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=📢 谷歌,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list

ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list

ruleset=📲 电报消息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list

; ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
; ruleset=📺 巴哈姆特,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.list
; ruleset=🎶 网易音乐,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
; ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list

ruleset=🌏 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
; ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list

; global 有问题
ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.list
; ruleset=🚀 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list

ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list


ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
;节点选择
custom_proxy_group=🚀 节点选择`select`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🎯 全球直连`[]1奶昔`[]4波奇`[]5XFSS`[]6XSUS`[]7魔戒`[]8良心云`[]3自建V6`[]2自建V4`[]🔯 金融家宽
custom_proxy_group=🔯 金融家宽`select`(irvine|home|家宽|HomeWideIP|Claw-Tokyo)
custom_proxy_group=🇭🇰 香港节点`select`(HK|HongKong|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|港|亚洲|香港|港(?!→|回))
custom_proxy_group=🇺🇲 美国节点`select`(US|America|United.*?States|美.*(?!→)|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|沪美|京美|美国)
;custom_proxy_group=🔯 故障转移`fallback`.*`http://cp.cloudflare.com/generate_204`300,,50

;自定分隔
custom_proxy_group=🎥 EMBY`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🔯 金融家宽`[]🚀 手动切换`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🌍 临时节点
custom_proxy_group=🌍 尚需直连`select`[]🎯 全球直连`[]🚀 节点选择`[]🔯 金融家宽`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🌍 临时节点
custom_proxy_group=🌍 开发相关`select`[]🔯 金融家宽`[]🇺🇲 美国节点`[]🇯🇵 日本节点`[]🎯 全球直连`[]🚀 节点选择`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🌍 临时节点
custom_proxy_group=🌍 PT站点`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 金融家宽`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🌍 临时节点
custom_proxy_group=🌍 美股券商`select`[]🔯 金融家宽`[]🇺🇲 美国节点`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🚀 节点选择`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🌍 临时节点

custom_proxy_group=📲 电报消息`select`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🔯 金融家宽`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇨🇳 台湾节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🎯 全球直连`[]🌍 临时节点
custom_proxy_group=📹 油管视频`select`[]🇺🇲 美国节点`[]🔯 金融家宽`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🎯 全球直连`[]🌍 临时节点
;custom_proxy_group=📹 油管音乐`select`[]🚀 节点选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🚀 手动切换`[]🎯 全球直连
; custom_proxy_group=🎥 奈飞视频`select`[]🇸🇬 狮城节点`[]🎥 奈飞节点`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🎯 全球直连
; custom_proxy_group=🎶 Spotify`select`[]🚀 节点选择`[]🔯 金融家宽`[]🎯 全球直连`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点
; custom_proxy_group=🎶 Tidal`select`[]🚀 节点选择`[]🎯 全球直连`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点

; custom_proxy_group=📺 巴哈姆特`select`[]🇨🇳 台湾节点`[]🇭🇰 香港节点`[]🚀 节点选择`[]🚀 手动切换`[]🎯 全球直连
; custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🚀 节点选择`[]🚀 手动切换`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点
; custom_proxy_group=🎶 网易音乐`select`[]🎯 全球直连`[]🚀 节点选择`(网易|音乐|解锁|Music|NetEase)

custom_proxy_group=📢 谷歌`select`[]🔯 金融家宽`[]🇺🇲 美国节点`[]🚀 节点选择`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🌍 临时节点
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]🔯 金融家宽`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🌍 临时节点

custom_proxy_group=Ⓜ️ 微软云盘`select`[]🎯 全球直连`[]🚀 节点选择`[]🔯 金融家宽`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🌍 临时节点
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]🔯 金融家宽`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🌍 临时节点
custom_proxy_group=🎥 Exhentai`select`[]🇺🇲 美国节点`[]🚀 节点选择`[]🔯 金融家宽`[]🚀 手动切换`[]🎯 全球直连`[]🇬🇧 欧洲节点`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🌍 临时节点
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🚀 节点选择`[]🔯 金融家宽`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🌍 临时节点
custom_proxy_group=🎮 SteamCN`select`[]🎯 全球直连`[]🚀 节点选择`[]🔯 金融家宽`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🌍 临时节点

custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]🔯 金融家宽`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🎯 全球直连`[]🌍 临时节点
custom_proxy_group=🌏 国内媒体`select`[]🎯 全球直连`[]🚀 节点选择`[]🔯 金融家宽`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]🌍 临时节点

custom_proxy_group=🎯 全球直连`select`[]DIRECT

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]🔯 金融家宽`[]🇭🇰 香港节点`[]🇨🇳 台湾节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇺🇲 美国节点`[]🇬🇧 欧洲节点`[]🇰🇷 韩国节点`[]🇹🇷 羊毛节点`[]🚀 手动切换`[]DIRECT`[]🌍 临时节点

; custom_proxy_group=🔯 金融家宽`select`(irvine|home|家宽|HomeWideIP)
; custom_proxy_group=🇭🇰 香港节点`select`(HK|HongKong|Hong.*?Kong|HKT|HKBN|HGC|WTT|CMI|港|亚洲|香港|港(?!→|回))
custom_proxy_group=🇯🇵 日本节点`select`(JP|Japan|日.*(?!→)|东京|大阪|埼玉|沪日|穗日|川日|中日|泉日|杭日|日本)
custom_proxy_group=🇨🇳 台湾节点`select`(台.*(?!→)|台北|台中|新北|彰化|TW|Taiwan|CHT|HiNet)
custom_proxy_group=🇸🇬 狮城节点`select`(SG|Singapore|新.*(?!→)|狮城|沪新|京新|泉新|穗新|深新|杭新)
; custom_proxy_group=🇺🇲 美国节点`select`(US|America|United.*?States|美.*(?!→)|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|沪美|京美|美国)
custom_proxy_group=🇰🇷 韩国节点`select`(KR|Korea|KOR|首尔|韩|韓)
; custom_proxy_group=🇲🇴 澳洲节点`select`(澳门|MO|Oman|Macao|澳.*(?!→)|CTM|新西兰|澳大利亚|Australia|Canada|加.*(?!→)|加拿大)
custom_proxy_group=🇬🇧 欧洲节点`select`(英|U.K|United Kingdom|UK|England|UnitedKingdom|欧洲|英.*(?!→)|伦敦|London|GM|柏林|Berlin|德|德国|DE|Germany|卢森堡|Luxembourg|芬兰|法|🇫🇷|FRA|巴黎|Paris|波兰|乌克兰|意大利|Italy|匈牙利|西班牙|Spain|荷|NL|Holland|Netherlands|瑞士|葡萄牙)
;custom_proxy_group=🇨🇳 台湾节点`url-test`(台.*(?!→)|台北|台中|新北|彰化|TW|Taiwan|CHT|HiNet)`http://cp.cloudflare.com/generate_204`300,,50
; custom_proxy_group=🇷🇺 俄罗斯节点`select`(RU|Russia|俄.*(?!→)|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄罗斯|京俄|杭俄|俄|莫斯科|新西伯利亚|Новосиби́рская|Moscow|RU|Russia)
; custom_proxy_group=🇮🇳 印度节点`select`(印|班加罗尔|孟买|Mumbai|IN|India|印.*(?!→))
custom_proxy_group=🇹🇷 羊毛节点`select`(RU|Russia|俄.*(?!→)|伯力|莫斯科|圣彼得堡|西伯利亚|新西伯利亚|哈巴罗夫斯克|俄罗斯|京俄|杭俄|俄|莫斯科|新西伯利亚|Новосиби́рская|Moscow|RU|Russia|阿根廷|Argentina|AR|Argentinaia|土耳其|TR|TUR|Turkey|巴基斯坦|印尼|柬埔寨|越南|Vietnam|泰国|Thailand|马来西亚|菲律宾|巴西|Brazil|瑞士|葡萄牙|墨西哥|尼日利亚|荷兰|爱沙尼亚|南美|智利|Chile|以色列|Israel|阿联酋|迪拜|Dubai|南非|ZA|South Africa|约翰内斯堡|Johannesburg|蒙古|哈萨克斯坦|印|班加罗尔|孟买|Mumbai|IN|India|印.*(?!→)|Indonesia|United Arab Emirates|Sweden|Bulgaria|Austria|Ireland|Hungary)

custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=🌍 临时节点`select`(GREEN|CUP|Fr|BWG|CONE|ORACLE|COLO|HomeWideIP|专线)
; custom_proxy_group=♻️ 自动选择`url-test`.*`http://cp.cloudflare.com/generate_204`300,,50
; custom_proxy_group=🎥 奈飞节点`select`(NF|奈飞|解锁|Netflix|NETFLIX|Media)

custom_proxy_group=1奶昔`select`!!GROUPID=0
; custom_proxy_group=1奶昔`url-test`!!GROUPID=0`http://cp.cloudflare.com/generate_204`90,,50
custom_proxy_group=2自建V4`select`!!GROUPID=1
; custom_proxy_group=2自建V4`url-test`!!GROUPID=1`http://cp.cloudflare.com/generate_204`90,,50
custom_proxy_group=3自建V6`select`!!GROUPID=2
; custom_proxy_group=3自建V6`url-test`!!GROUPID=2`http://cp.cloudflare.com/generate_204`90,,50
custom_proxy_group=4波奇`select`!!GROUPID=3
; custom_proxy_group=4波奇`url-test`!!GROUPID=3`http://cp.cloudflare.com/generate_204`90,,50
custom_proxy_group=5XFSS`select`!!GROUPID=4
; custom_proxy_group=5XFSS`url-test`!!GROUPID=4`http://cp.cloudflare.com/generate_204`90,,50
custom_proxy_group=6XSUS`select`!!GROUPID=5
; custom_proxy_group=6XSUS`url-test`!!GROUPID=5`http://cp.cloudflare.com/generate_204`90,,50
custom_proxy_group=7魔戒`select`!!GROUPID=6
; custom_proxy_group=7魔戒`url-test`!!GROUPID=6`http://cp.cloudflare.com/generate_204`90,,50
custom_proxy_group=8良心云`select`!!GROUPID=7
; custom_proxy_group=8良心云`url-test`!!GROUPID=7`http://cp.cloudflare.com/generate_204`90,,50
;设置分组标志位

; custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
; custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
; custom_proxy_group=🆎 AdBlock`select`[]REJECT`[]DIRECT
; custom_proxy_group=🛡️ 隐私防护`select`[]REJECT`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true

; clash_rule_base=https://raw.githubusercontent.com/ResidualBlood/Clash_Rules/master/Myself/GeneralClashConfig_V6.yml

;luck
